project_id = "msrjlhuaipomregrijqi"

[functions.fetch-github-repos]
verify_jwt = false

[functions.fetch-medium-feed]
verify_jwt = false

[functions.fetch-mastodon-feed]
verify_jwt = false

[functions.fetch-bluesky-feed]
verify_jwt = false

[functions.fetch-strava-activities]
verify_jwt = false

[functions.strava-token-exchange]
verify_jwt = false
